# Nombre de la aplicación
spring.application.name=smartclinic-api

# Configuración de PostgreSQL (Asegúrate de poner tu usuario y contraseña de Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/smartclinic_db
spring.datasource.username=postgres
spring.datasource.password=15963
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
